
# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list=
organization:
    - instituto-nacional-de-estudos-e-pesquisas-educacionais-inep

dataset_id: br_inep_enem

title: Exame Nacional do Ensino Médio (ENEM)

# exemplo: descrição e anotações úteis sobre os dados.
description:

# Quais grupos caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
groups: []

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags: []

ckan_url:

github_url:

metadata_modified: '2021-11-16T10:02:35.259598'
