
dataset_id: br_inep_enem

table_id: escola

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Microdados do Exame Nacional do Ensino Médio por escola

# A máxima unidade espacial que a tabela cobre.
spatial_coverage: bra

# Anos cobertos pela tabela.
temporal_coverage:
    - 2005
    - 2006
    - 2007
    - 2008
    - 2009
    - 2010
    - 2011
    - 2012
    - 2013
    - 2014
    - 2015

# A unidade temporal com qual a tabela é atualizada.
update_frequency: unique

# Entidade representada por cada linha.
entity: school

# A unidade temporal representada por cada linha.
time_unit: unique

# O conjunto mínimo de colunas identificando cada linha unicamente.
# Preencha com os nomes de colunas. Ex: id_municipio, ano.
# Pode ser vazio pois certas tabelas não possuem identificadores.
identifying_columns: 
    - ano
    - id_escola

last_updated:
    metadata:
    data:
    release:

version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Lucas Moreira
    email: lucas.moreira@basedosdados.org
    github_user: lucasnascm
    website:
    ckan_user: lucasnascm

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Lucas Moreira
    email: lucas.moreira@basedosdados.org
    github_user: lucasnascm
    ckan_user: lucasnascm
    website:
    code_url: https://github.com/basedosdados/mais/tree/master/bases/br_inep_enem/code

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: "Download dos microdados do INEP \n
                            Padronização das variáveis \n
                            Formação de dicionário para 'nivel_socioeconomico' e porte_escola' \n
                            Ordenação das variáveis"

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

covered_by_dictionary: yes

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

bdm_file_size:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage: 
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf 
          column_name: sigla 
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: id_municipio
      bigquery_type: string
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column: 
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: id_escola
      bigquery_type: string
      description: ID Escola - INEP
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: escola
          column_name: id_escola
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: rede
      bigquery_type: string
      description: Rede Escolar
      temporal_coverage:
      covered_by_dictionary: 
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: tipo_localizacao
      bigquery_type: string
      description: Localização da escola
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: nivel_socio_economico
      bigquery_type: string
      description: Nível socioecônomico da escola baseado no INSE
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: formacao_docente
      bigquery_type: string
      description: Indicador de Adequação da Formação Docente
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: porte_escola
      bigquery_type: string
      description: Tamanho da escola pelo número de alunos matriculados
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: alunos_matriculados
      bigquery_type: int64
      description: Número de alunos matriculados no Censo Escolar na 3ª e 4ª do Ensino Médio.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: participantes_enem
      bigquery_type: int64
      description: Número de participantes do Enem que cumprem os requisitos de participação no cálculo da média.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: participantes_enem_necessidade_especial
      bigquery_type: int64
      description: Número de participantes do Enem que cumprem os requisitos de participação no cálculo da média e possui necessidade especial.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: media_ciencias_natureza
      bigquery_type: float64
      description: Média das notas de Ciências da Natureza do Ensino Médio Regular
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: media_ciencias_humanas
      bigquery_type: float64
      description: Média das notas de Ciências Humanas do Ensino Médio Regular
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: media_linguagens_codigos
      bigquery_type: float64
      description: Média das notas de Linguagens e Códigos do Ensino Médio Regular
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: media_matematica
      bigquery_type: float64
      description: Média das notas de Matemática do Ensino Médio Regular
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: media_redacao
      bigquery_type: float64
      description: Média das notas de Redação do Ensino Médio Regular
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: media_prova_objetiva
      bigquery_type: float64
      description: Média da prova objetiva do Ensino Médio Regular
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: media_total
      bigquery_type: float64
      description: Média Total (Redação e Prova Objetiva) Ensino Médio Regular corrigida pelo número de participantes
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: taxa_participacao
      bigquery_type: float64
      description: Número total de participantes no ENEM da escola dividido pelo número de matriculados nos anos finais do Ensino Médio da escola
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: taxa_permanencia
      bigquery_type: float64
      description: Indicador de Permanência na Escola para o Ensino Médio
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: taxa_aprovacao
      bigquery_type: float64
      description: Taxa de aprovação dos alunos no Ensino Médio
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: taxa_reprovacao
      bigquery_type: float64
      description: Taxa de reprovação dos alunos no Ensino Médio
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: taxa_abandono
      bigquery_type: float64
      description: Taxa de abandono dos alunos no Ensino Médio
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: percent
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false

metadata_modified:
