
dataset_id: br_mc_auxilio_emergencial

table_id: microdados

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: "Microdados do auxílio emergencial de 2020 do Ministério da Cidadania\
    \ a nível de indivíduo.\n"

# A máxima unidade espacial que a tabela cobre.
spatial_coverage:
    continent:
        - south_america
    country:
        - bra

# Anos cobertos pela tabela.
temporal_coverage:
    - 2020
    - 2021

# A unidade temporal com qual a tabela é atualizada.
update_frequency: month

# Entidade representada por cada linha.
entity:
    - person

# A unidade temporal representada por cada linha.
time_unit: month

# O conjunto mínimo de colunas identificando cada linha unicamente.
# Preencha com os nomes de colunas. Ex: id_municipio, ano.
# Pode ser vazio pois certas tabelas não possuem identificadores.
identifying_columns:
    - mes
    - id_municipio
    - nis_beneficiario
    - cpf_beneficiario
    - nome_beneficiario
    - parcela

last_updated:
    metadata:
    data:
    release:

version: v1.0

# Quem está preenchendo esses metadados?
published_by:
    name: Ricardo Dahis
    email: rdahis@basedosdados.org
    github_user: ''
    website: www.ricardodahis.com
    ckan_user: ''

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Ricardo Dahis
    email: rdahis@basedosdados.org
    github_user: ''
    ckan_user: ''
    website: http://www.portaltransparencia.gov.br/beneficios/auxilio-emergencial
    code_url: https://github.com/basedosdados/mais/tree/master/bases/br_mc_auxilio_emergencial/code

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: "Limpeza para consistência. Mudamos o formato da variável\
    \ mês. Transformamos os valores NA para vazio.\n"

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

covered_by_dictionary:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions: mes, sigla_uf

bdm_file_size: Unavailable

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: mes
      bigquery_type:
      description: Mês
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: true
    - name: sigla_uf
      bigquery_type:
      description: Sigla da Unidade da Federação
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: true
    - name: id_municipio
      bigquery_type:
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: nis_beneficiario
      bigquery_type:
      description: Número de Identificação Social (NIS) do beneficiário do Auxílio
          Emergencial, caso possua.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: cpf_beneficiario
      bigquery_type:
      description: Número no Cadastro de Pessoas Físicas (CPF) do beneficiário do
          Auxílio Emergencial, caso possua.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: nome_beneficiario
      bigquery_type:
      description: Nome do beneficiário do Auxílio Emergencial.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: nis_responsavel
      bigquery_type:
      description: Número de Identificação Social (NIS) do responsável pelo beneficiário
          do Auxílio Emergencial, caso possua.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: cpf_responsavel
      bigquery_type:
      description: Número no Cadastro de Pessoas Físicas (CPF) do responsável pelo
          beneficiário do Auxílio Emergencial, caso possua.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: nome_responsavel
      bigquery_type:
      description: Nome do responsável pelo beneficiário do Auxílio Emergencial, caso
          possua.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: enquadramento
      bigquery_type:
      description: Identifica se o beneficiário é do grupo Bolsa Família, Inscrito
          no Cadastro Único (CadÚnico) ou Não Inscrito no Cadastro Único (ExtraCad).
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: parcela
      bigquery_type:
      description: Número sequencial da parcela disponibilizada.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: observacao
      bigquery_type:
      description: Indica alterações na parcela disponibilizada como, por exemplo,
          se foi devolvida ou está retida.
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: valor_beneficio
      bigquery_type:
      description: Valor do Benefício (R$)
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false

metadata_modified: '2021-10-28T16:04:39.374368'
