
dataset_id: br_inep_enem

table_id: dicionario

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Dicionário para a base do Exame Nacional do Ensino Médio (ENEM).

# A máxima unidade espacial que a tabela cobre.
spatial_coverage:

# Anos cobertos pela tabela.
temporal_coverage:

# A unidade temporal com qual a tabela é atualizada.
update_frequency: unique

# Entidade representada por cada linha.
entity:

# A unidade temporal representada por cada linha.
time_unit: unique

# O conjunto mínimo de colunas identificando cada linha unicamente.
# Preencha com os nomes de colunas. Ex: id_municipio, ano.
# Pode ser vazio pois certas tabelas não possuem identificadores.
identifying_columns: 
    - id_chave
    - coluna
    - chave
    - cobertura_temporal

last_updated:
    metadata:
    data:
    release:

version: ''

# Quem está preenchendo esses metadados?
published_by:
    name: Lucas Moreira
    email: lucas.moreira@basedosdados.org
    github_user: lucasnascm
    website:
    ckan_user: lucasnascm

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Lucas Moreira
    email: lucas.moreira@basedosdados.org
    github_user: lucasnascm
    ckan_user: lucasnascm
    website:
    code_url: https://github.com/basedosdados/mais/tree/master/bases/br_inep_enem/code

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: Compatibilização dos dicionários do INEP

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

covered_by_dictionary:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

bdm_file_size:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: id_tabela
      bigquery_type: string
      description: ID Tabela
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: nome_coluna
      bigquery_type: string
      description: Nome da coluna
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: chave
      bigquery_type: string
      description: Chave
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: cobertura_temporal
      bigquery_type: string
      description: Cobertura Temporal
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false
    - name: valor
      bigquery_type: string
      description: Valor
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition: false

metadata_modified: '2021-11-14T20:00:56.246008'
