
dataset_id: mundo_coinmarketcap_criptmoeda

table_id: bitcoin

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description: Série histórica com dados diários preços de mercado do bitcoin

# A máxima unidade espacial que a tabela cobre.
spatial_coverage: all

# Anos cobertos pela tabela.
temporal_coverage:
    - 2013
    - 2014
    - 2015
    - 2016
    - 2017
    - 2018
    - 2019
    - 2020
    - 2021

# A unidade temporal com qual a tabela é atualizada.
update_frequency: day

# Entidade representada por cada linha.
entity: transaction

# A unidade temporal representada por cada linha.
time_unit: day

# O conjunto mínimo de colunas identificando cada linha unicamente.
# Preencha com os nomes de colunas. Ex: id_municipio, ano.
# Pode ser vazio pois certas tabelas não possuem identificadores.
identifying_columns: data

last_updated:
    metadata:
    data:
    release:

version:

# Quem está preenchendo esses metadados?
published_by:
    name: Lucas Nobre Barbosa
    email: lucasbnobre18@gmail.com
    github_user: nobre-lucas
    website:
    ckan_user: 

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name: Lucas Nobre Barbosa
    email: lucasbnobre18@gmail.com
    github_user: nobre-lucas
    ckan_user:
    website:
    code_url: https://github.com/basedosdados/mais/tree/master/bases/mundo_coinmarketcap_criptmoeda/code

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description: "Scrapping do site \n
    Organização das colunas e renomeação delas \n
    Divisão das colunas de data e hora \n
    Conversão pra .csv"

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

covered_by_dictionary: no

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions:

bdm_file_size:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: data
      bigquery_type: date
      description: Data
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: data
          column_name: data
      measurement_unit: day
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: hora_maior_preco
      bigquery_type: time
      description: Hora do maior preço
      temporal_coverage: 
      covered_by_dictionary: yes
      directory_column: 
          dataset_id: br_bd_diretorios_data_tempo
          table_id: hora
          column_name: hora
      measurement_unit: second
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: hora_menor_preco
      bigquery_type: time
      description: Hora do menor preço
      temporal_coverage: 
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: hora
          column_name: hora
      measurement_unit: second
      has_sensitive_data:
      is_in_staging:
      is_partition:
    - name: preco_abertura
      bigquery_type: float64
      description: Preço do bitcoin na abertura do mercado
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: maior_preco
      bigquery_type: float64
      description: Maior preço por dia 
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: menor_preco
      bigquery_type: float64
      description: Menor preço do dia
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: preco_encerramento
      bigquery_type: float64
      description: Preço do bitcoin no encerramento do mercado
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: usd
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: volume
      bigquery_type: float64
      description: Volume de bitcoin transacionado no dia
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false
    - name: capitalizacao_mercado
      bigquery_type: float64
      description: Valuation da moeda no dia
      temporal_coverage:
      covered_by_dictionary:
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: true
      is_partition: false

metadata_modified:
